const data=[
    {"name": "Lamball", "rarity": 1, "skills": {"Handiwork" : 1, "Farming" : 1, "Transporting" : 1}, "index" : 1, "element" : ["elm9"]},
    {"name": "Cattiva", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Mining" : 1, "Transporting" : 1}, "index" : 2, "element" : ["elm9"]},
    {"name": "Chikipi", "rarity": 1, "skills": {"Gathering" : 1, "Farming" : 1}, "index" : 3, "element" : ["elm5"]},
    {"name": "Lifmunk", "rarity": 1, "skills": {"Gathering" : 1, "Deforesting" : 1, "Handiwork" : 1, "Medicine Production" : 1, "Planting" : 1}, "index" : 4, "element" : ["elm8"]},
    {"name": "Foxparks", "rarity": 1, "skills": {"Kindling" : 1}, "index" : 5, "element" : ["elm7"]},
    {"name": "Fuack", "rarity": 1, "skills": {"Handiwork" : 1, "Transporting" : 1, "Watering" : 1}, "index" : 6, "element" : ["elm6"]},
    {"name": "Sparkit", "rarity": 1, "skills": {"Generating Electricity" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 7, "element" : ["elm5"]},
    {"name": "Tanzee", "rarity": 1, "skills": {"Gathering" : 1, "Deforesting" : 1, "Handiwork" : 1, "Planting" : 1, "Transporting" : 1}, "index" : 8, "element" : ["elm8"]},
    {"name": "Rooby", "rarity": 2, "skills": {"Kindling" : 1}, "index" : 9, "element" : ["elm7","elm1"]},
    {"name": "Pengullet", "rarity": 1, "skills": {"Cooling" : 1, "Handiwork" : 1, "Transporting" : 1, "Watering" : 1}, "index" : 10, "element" : ["elm7","elm1"]},
    {"name": "Penking", "rarity": 6, "skills": {"Cooling" : 2, "Handiwork" : 2, "Mining" : 2, "Transporting" : 2, "Watering" : 2}, "index" : 11, "element" : ["elm6"]},
    {"name": "Jolthog", "rarity": 1, "skills": {"Generating Electricity" : 1}, "index" : 12, "element" : ["elm1"]},
    {"name": "Jolthog Cryst", "rarity": 2, "skills": {"Cooling" : 1}, "index" : 12, "element" : ["elm5","elm4"]},
    {"name": "Gumoss", "rarity": 1, "skills": {"Planting" : 1}, "index" : 13, "element" : ["elm9"]},
    {"name": "Vixy", "rarity": 2, "skills": {"Gathering" : 1, "Farming" : 1}, "index" : 14, "element" : ["elm2"]},
    {"name": "Hoocrates", "rarity": 1, "skills": {"Gathering" : 1}, "index" : 15, "element" : ["elm7"]},
    {"name": "Teafant", "rarity": 1, "skills": {"Watering" : 1}, "index" : 16, "element" : ["elm2"]},
    {"name": "Depresso", "rarity": 1, "skills": {"Handiwork" : 1, "Mining" : 1, "Transporting" : 1}, "index" : 17, "element" : ["elm9"]},
    {"name": "Cremis", "rarity": 1, "skills": {"Gathering" : 1, "Farming" : 1}, "index" : 18, "element" : ["elm2"]},
    {"name": "Daedream", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 19, "element" : ["elm4"]},
    {"name": "Rushoar", "rarity": 1, "skills": {"Mining" : 1}, "index" : 20, "element" : ["elm2"]},
    {"name": "Nox", "rarity": 6, "skills": {"Gathering" : 1}, "index" : 21, "element" : ["elm4"]},
    {"name": "Fuddler", "rarity": 1, "skills": {"Handiwork" : 1, "Mining" : 1, "Transporting" : 1}, "index" : 22, "element" : ["elm2"]},
    {"name": "Killamari", "rarity": 1, "skills": {"Gathering" : 1, "Transporting" : 2}, "index" : 23, "element" : ["elm2"]},
    {"name": "Mau", "rarity": 1, "skills": {"Farming" : 1}, "index" : 24, "element" : ["elm1"]},
    {"name": "Mau Cryst", "rarity": 2, "skills": {"Cooling" : 1, "Farming" : 1}, "index" : 24, "element" : ["elm7"]},
    {"name": "Celaray", "rarity": 3, "skills": {"Transporting" : 1, "Watering" : 1}, "index" : 25, "element" : ["elm9"]},
    {"name": "Direhowl", "rarity": 2, "skills": {"Gathering" : 1}, "index" : 26, "element" : ["elm9"]},
    {"name": "Tocotoco", "rarity": 1, "skills": {"Gathering" : 1}, "index" : 27, "element" : ["elm5"]},
    {"name": "Flopie", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Medicine Production" : 1, "Planting" : 1, "Transporting" : 1}, "index" : 28, "element" : ["elm7"]},
    {"name": "Mozzarina", "rarity": 2, "skills": {"Farming" : 1}, "index" : 29, "element" : ["elm5"]},
    {"name": "Bristla", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Medicine Production" : 2, "Planting" : 1, "Transporting" : 1}, "index" : 30, "element" : ["elm7"]},
    {"name": "Gobfin", "rarity": 2, "skills": {"Handiwork" : 1, "Transporting" : 1, "Watering" : 2}, "index" : 31, "element" : ["elm8"]},
    {"name": "Gobfin Ignis", "rarity": 3, "skills": {"Kindling" : 2, "Handiwork" : 1, "Transporting" : 1}, "index" : 31, "element" : ["elm4"]},
    {"name": "Hangyu", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Transporting" : 2}, "index" : 32, "element" : ["elm1"]},
    {"name": "Hangyu Cryst", "rarity": 2, "skills": {"Gathering" : 1, "Cooling" : 1, "Handiwork" : 1, "Transporting" : 2}, "index" : 32, "element" : ["elm5"]},
    {"name": "Mossanda", "rarity": 6, "skills": {"Deforesting" : 2, "Handiwork" : 2, "Planting" : 2, "Transporting" : 3}, "index" : 33, "element" : ["elm6"]},
    {"name": "Mossanda Lux", "rarity": 7, "skills": {"Deforesting" : 2, "Generating Electricity" : 2, "Handiwork" : 2, "Transporting" : 3}, "index" : 33, "element" : ["elm9"]},
    {"name": "Woolipop", "rarity": 3, "skills": {"Farming" : 1}, "index" : 34, "element" : ["elm5"]},
    {"name": "Caprity", "rarity": 3, "skills": {"Farming" : 1, "Planting" : 2}, "index" : 35, "element" : ["elm9"]},
    {"name": "Melpaca", "rarity": 3, "skills": {"Farming" : 1}, "index" : 36, "element" : ["elm9"]},
    {"name": "Eikthyrdeer", "rarity": 4, "skills": {"Deforesting" : 2}, "index" : 37, "element" : ["elm4"]},
    {"name": "Eikthyrdeer Terra", "rarity": 6, "skills": {"Deforesting" : 2}, "index" : 37, "element" : ["elm9"]},
    {"name": "Nitewing", "rarity": 3, "skills": {"Gathering" : 2}, "index" : 38, "element" : ["elm9"]},
    {"name": "Ribbuny", "rarity": 1, "skills": {"Gathering" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 39, "element" : ["elm8","elm2"]},
    {"name": "Incineram", "rarity": 4, "skills": {"Kindling" : 1, "Handiwork" : 2, "Mining" : 1, "Transporting" : 2}, "index" : 40, "element" : ["elm2"]},
    {"name": "Incineram Noct", "rarity": 5, "skills": {"Handiwork" : 2, "Mining" : 1, "Transporting" : 2}, "index" : 40, "element" : ["elm5"]},
    {"name": "Cinnamoth", "rarity": 4, "skills": {"Medicine Production" : 1, "Planting" : 2}, "index" : 41, "element" : ["elm8"]},
    {"name": "Arsox", "rarity": 4, "skills": {"Deforesting" : 1, "Kindling" : 2}, "index" : 42, "element" : ["elm4"]},
    {"name": "Dumud", "rarity": 4, "skills": {"Mining" : 2, "Farming" : 1, "Oil Extracting" : 1, "Transporting" : 1, "Watering" : 1}, "index" : 43, "element" : ["elm2"]},
    {"name": "Cawgnito", "rarity": 3, "skills": {"Deforesting" : 1}, "index" : 44, "element" : ["elm2"]},
    {"name": "Leezpunk", "rarity": 2, "skills": {"Gathering" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 45, "element" : ["elm8"]},
    {"name": "Leezpunk Ignis", "rarity": 3, "skills": {"Gathering" : 1, "Kindling" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 45, "element" : ["elm2"]},
    {"name": "Loupmoon", "rarity": 2, "skills": {"Handiwork" : 2}, "index" : 46, "element" : ["elm9"]},
    {"name": "Galeclaw", "rarity": 2, "skills": {"Gathering" : 2}, "index" : 47, "element" : ["elm5"]},
    {"name": "Robinquill", "rarity": 5, "skills": {"Gathering" : 2, "Deforesting" : 1, "Handiwork" : 2, "Medicine Production" : 1, "Planting" : 1, "Transporting" : 2}, "index" : 48, "element" : ["elm5","elm4"]},
    {"name": "Robinquill Terra", "rarity": 6, "skills": {"Gathering" : 2, "Deforesting" : 1, "Handiwork" : 2, "Medicine Production" : 1, "Transporting" : 2}, "index" : 48, "element" : ["elm9"]},
    {"name": "Gorirat", "rarity": 5, "skills": {"Deforesting" : 2, "Handiwork" : 1, "Transporting" : 3}, "index" : 49, "element" : ["elm5"]},
    {"name": "Beegarde", "rarity": 4, "skills": {"Gathering" : 1, "Deforesting" : 1, "Handiwork" : 1, "Farming" : 1, "Medicine Production" : 1, "Planting" : 1, "Transporting" : 2}, "index" : 50, "element" : ["elm5"]},
    {"name": "Elizabee", "rarity": 8, "skills": {"Gathering" : 2, "Deforesting" : 1, "Handiwork" : 2, "Medicine Production" : 2, "Planting" : 2}, "index" : 51, "element" : ["elm9"]},
    {"name": "Grintale", "rarity": 6, "skills": {"Gathering" : 2}, "index" : 52, "element" : ["elm1"]},
    {"name": "Swee", "rarity": 1, "skills": {"Gathering" : 1, "Cooling" : 1}, "index" : 53, "element" : ["elm1"]},
    {"name": "Sweepa", "rarity": 6, "skills": {"Gathering" : 2, "Cooling" : 2}, "index" : 54, "element" : ["elm1","elm3"]},
    {"name": "Chillet", "rarity": 4, "skills": {"Gathering" : 1, "Cooling" : 1}, "index" : 55, "element" : ["elm6"]},
    {"name": "Univolt", "rarity": 5, "skills": {"Deforesting" : 1, "Generating Electricity" : 2}, "index" : 56, "element" : ["elm1"]},
    {"name": "Foxcicle", "rarity": 5, "skills": {"Cooling" : 2}, "index" : 57, "element" : ["elm8"]},
    {"name": "Pyrin", "rarity": 6, "skills": {"Deforesting" : 1, "Kindling" : 2}, "index" : 58, "element" : ["elm8","elm2"]},
    {"name": "Pyrin Noct", "rarity": 7, "skills": {"Deforesting" : 1, "Kindling" : 2}, "index" : 58, "element" : ["elm1"]},
    {"name": "Reindrix", "rarity": 4, "skills": {"Cooling" : 2, "Deforesting" : 2}, "index" : 59, "element" : ["elm6"]},
    {"name": "Rayhound", "rarity": 5, "skills": {"Generating Electricity" : 2}, "index" : 60, "element" : ["elm8"]},
    {"name": "Kitsun", "rarity": 6, "skills": {"Kindling" : 2}, "index" : 61, "element" : ["elm6"]},
    {"name": "Dazzi", "rarity": 2, "skills": {"Generating Electricity" : 1, "Handiwork" : 1, "Transporting" : 1}, "index" : 62, "element" : ["elm9"]},
    {"name": "Lunaris", "rarity": 6, "skills": {"Gathering" : 1, "Handiwork" : 3, "Transporting" : 1}, "index" : 63, "element" : ["elm5","elm3"]},
    {"name": "Dinossom", "rarity": 6, "skills": {"Deforesting" : 2, "Planting" : 2}, "index" : 64, "element" : ["elm6","elm3"]},
    {"name": "Dinossom Lux", "rarity": 7, "skills": {"Deforesting" : 2, "Generating Electricity" : 2}, "index" : 64, "element" : ["elm7"]},
    {"name": "Surfent", "rarity": 4, "skills": {"Watering" : 2}, "index" : 65, "element" : ["elm4"]},
    {"name": "Surfent Terra", "rarity": 5, "skills": {"Gathering" : 1}, "index" : 65, "element" : ["elm2"]},
    {"name": "Maraith", "rarity": 6, "skills": {"Gathering" : 2, "Mining" : 1}, "index" : 66, "element" : ["elm4"]},
    {"name": "Digtoise", "rarity": 5, "skills": {"Mining" : 3}, "index" : 67, "element" : ["elm2"]},
    {"name": "Tombat", "rarity": 5, "skills": {"Gathering" : 2, "Mining" : 2, "Transporting" : 2}, "index" : 68, "element" : ["elm9"]},
    {"name": "Lovander", "rarity": 5, "skills": {"Handiwork" : 2, "Mining" : 1, "Medicine Production" : 2, "Transporting" : 2}, "index" : 69, "element" : ["elm8"]},
    {"name": "Flambelle", "rarity": 1, "skills": {"Kindling" : 1, "Handiwork" : 1, "Farming" : 1, "Transporting" : 1}, "index" : 70, "element" : ["elm8","elm2"]},
    {"name": "Vanwyrm", "rarity": 4, "skills": {"Kindling" : 1, "Transporting" : 3}, "index" : 71, "element" : ["elm1","elm2"]},
    {"name": "Vanwyrm Cryst", "rarity": 5, "skills": {"Cooling" : 2, "Transporting" : 3}, "index" : 71, "element" : ["elm8"]},
    {"name": "Bushi", "rarity": 7, "skills": {"Gathering" : 1, "Deforesting" : 3, "Kindling" : 2, "Handiwork" : 1, "Transporting" : 2}, "index" : 72, "element" : ["elm6"]},
    {"name": "Beakon", "rarity": 6, "skills": {"Gathering" : 1, "Generating Electricity" : 2, "Transporting" : 3}, "index" : 73, "element" : ["elm8"]},
    {"name": "Ragnahawk", "rarity": 7, "skills": {"Kindling" : 3, "Transporting" : 3}, "index" : 74, "element" : ["elm2"]},
    {"name": "Katress", "rarity": 6, "skills": {"Handiwork" : 2, "Medicine Production" : 2, "Transporting" : 2}, "index" : 75, "element" : ["elm8"]},
    {"name": "Wixen", "rarity": 6, "skills": {"Kindling" : 2, "Handiwork" : 3, "Transporting" : 2}, "index" : 76, "element" : ["elm5"]},
    {"name": "Verdash", "rarity": 8, "skills": {"Gathering" : 3, "Deforesting" : 2, "Handiwork" : 3, "Planting" : 2, "Transporting" : 2}, "index" : 77, "element" : ["elm5"]},
    {"name": "Vaelet", "rarity": 8, "skills": {"Gathering" : 2, "Handiwork" : 2, "Medicine Production" : 3, "Planting" : 2, "Transporting" : 1}, "index" : 78, "element" : ["elm1"]},
    {"name": "Sibelyx", "rarity": 7, "skills": {"Cooling" : 2, "Farming" : 1, "Medicine Production" : 2}, "index" : 79, "element" : ["elm3"]},
    {"name": "Elphidran", "rarity": 7, "skills": {"Deforesting" : 2}, "index" : 80, "element" : ["elm3","elm7"]},
    {"name": "Elphidran Aqua", "rarity": 8, "skills": {"Deforesting" : 2, "Watering" : 3}, "index" : 80, "element" : ["elm7"]},
    {"name": "Kelpsea", "rarity": 1, "skills": {"Farming" : 1, "Watering" : 1}, "index" : 81, "element" : ["elm8"]},
    {"name": "Kelpsea Ignis", "rarity": 2, "skills": {"Kindling" : 1, "Farming" : 1}, "index" : 81, "element" : ["elm7","elm3"]},
    {"name": "Azurobe", "rarity": 7, "skills": {"Watering" : 3}, "index" : 82, "element" : ["elm1"]},
    {"name": "Cryolinx", "rarity": 7, "skills": {"Cooling" : 3, "Deforesting" : 2, "Handiwork" : 1}, "index" : 83, "element" : ["elm8"]},
    {"name": "Blazehowl", "rarity": 7, "skills": {"Deforesting" : 2, "Kindling" : 3}, "index" : 84, "element" : ["elm8","elm2"]},
    {"name": "Blazehowl Noct", "rarity": 8, "skills": {"Deforesting" : 2, "Kindling" : 3}, "index" : 84, "element" : ["elm3","elm7"]},
    {"name": "Relaxaurus", "rarity": 8, "skills": {"Transporting" : 1, "Watering" : 2}, "index" : 85, "element" : ["elm3","elm6"]},
    {"name": "Relaxaurus Lux", "rarity": 9, "skills": {"Generating Electricity" : 3, "Transporting" : 1}, "index" : 85, "element" : ["elm5"]},
    {"name": "Broncherry", "rarity": 7, "skills": {"Planting" : 3}, "index" : 86, "element" : ["elm5","elm7"]},
    {"name": "Broncherry Aqua", "rarity": 8, "skills": {"Watering" : 3}, "index" : 86, "element" : ["elm5"]},
    {"name": "Petallia", "rarity": 8, "skills": {"Gathering" : 2, "Handiwork" : 2, "Medicine Production" : 2, "Planting" : 3, "Transporting" : 1}, "index" : 87, "element" : ["elm8","elm4"]},
    {"name": "Reptyro", "rarity": 6, "skills": {"Kindling" : 3, "Mining" : 3}, "index" : 88, "element" : ["elm1","elm4"]},
    {"name": "Reptyro Cryst", "rarity": 7, "skills": {"Cooling" : 3, "Mining" : 3}, "index" : 88, "element" : ["elm9"]},
    {"name": "Kingpaca", "rarity": 8, "skills": {"Gathering" : 1}, "index" : 89, "element" : ["elm1"]},
    {"name": "Kingpaca Cryst", "rarity": 9, "skills": {"Gathering" : 1, "Cooling" : 3}, "index" : 89, "element" : ["elm5"]},
    {"name": "Mammorest", "rarity": 8, "skills": {"Deforesting" : 2, "Mining" : 2, "Planting" : 2}, "index" : 90, "element" : ["elm1"]},
    {"name": "Mammorest Cryst", "rarity": 9, "skills": {"Deforesting" : 2, "Mining" : 2, "Planting" : 2}, "index" : 90, "element" : ["elm9"]},
    {"name": "Wumpo", "rarity": 7, "skills": {"Cooling" : 2, "Deforesting" : 3, "Handiwork" : 2, "Transporting" : 4}, "index" : 91, "element" : ["elm5"]},
    {"name": "Wumpo Botan", "rarity": 8, "skills": {"Deforesting" : 3, "Handiwork" : 2, "Planting" : 1, "Transporting" : 4}, "index" : 91, "element" : ["elm4","elm5"]},
    {"name": "Warsect", "rarity": 8, "skills": {"Deforesting" : 3, "Handiwork" : 1, "Planting" : 1, "Transporting" : 3}, "index" : 92, "element" : ["elm9"]},
    {"name": "Fenglope", "rarity": 3, "skills": {"Deforesting" : 2}, "index" : 93, "element" : ["elm2"]},
    {"name": "Felbat", "rarity": 6, "skills": {"Medicine Production" : 3}, "index" : 94, "element" : ["elm3"]},
    {"name": "Quivern", "rarity": 7, "skills": {"Gathering" : 2, "Handiwork" : 1, "Mining" : 2, "Transporting" : 3}, "index" : 95, "element" : ["elm8"]},
    {"name": "Blazamut", "rarity": 9, "skills": {"Kindling" : 3, "Mining" : 4}, "index" : 96, "element" : ["elm2"]},
    {"name": "Helzephyr", "rarity": 7, "skills": {"Transporting" : 3}, "index" : 97, "element" : ["elm3","elm2"]},
    {"name": "Astegon", "rarity": 9, "skills": {"Handiwork" : 1, "Mining" : 4, "Oil Extracting" : 3}, "index" : 98, "element" : ["elm2","elm4"]},
    {"name": "Menasting", "rarity": 9, "skills": {"Deforesting" : 2, "Mining" : 3}, "index" : 99, "element" : ["elm4"]},
    {"name": "Anubis", "rarity": 10, "skills": {"Handiwork" : 4, "Mining" : 3, "Transporting" : 2}, "index" : 100, "element" : ["elm3","elm7"]},
    {"name": "Jormuntide", "rarity": 8, "skills": {"Watering" : 4}, "index" : 101, "element" : ["elm3","elm8"]},
    {"name": "Jormuntide Ignis", "rarity": 9, "skills": {"Kindling" : 4}, "index" : 101, "element" : ["elm8"]},
    {"name": "Suzaku", "rarity": 8, "skills": {"Kindling" : 3}, "index" : 102, "element" : ["elm7"]},
    {"name": "Suzaku Aqua", "rarity": 9, "skills": {"Watering" : 3}, "index" : 102, "element" : ["elm6"]},
    {"name": "Grizzbolt", "rarity": 8, "skills": {"Deforesting" : 2, "Generating Electricity" : 3, "Handiwork" : 2, "Transporting" : 3}, "index" : 103, "element" : ["elm5"]},
    {"name": "Lyleen", "rarity": 9, "skills": {"Gathering" : 2, "Handiwork" : 3, "Medicine Production" : 3, "Planting" : 4}, "index" : 104, "element" : ["elm2"]},
    {"name": "Lyleen Noct", "rarity": 10, "skills": {"Gathering" : 2, "Handiwork" : 3, "Medicine Production" : 3}, "index" : 104, "element" : ["elm8"]},
    {"name": "Faleris", "rarity": 9, "skills": {"Kindling" : 3, "Transporting" : 3}, "index" : 105, "element" : ["elm3","elm6"]},
    {"name": "Orserk", "rarity": 10, "skills": {"Generating Electricity" : 4, "Handiwork" : 2, "Transporting" : 3}, "index" : 106, "element" : ["elm2"]},
    {"name": "Shadowbeak", "rarity": 10, "skills": {"Gathering" : 1}, "index" : 107, "element" : ["elm9"]},
    {"name": "Paladius", "rarity": 20, "skills": {"Deforesting" : 2, "Mining" : 2}, "index" : 108, "element" : ["elm2"]},
    {"name": "Necromus", "rarity": 20, "skills": {"Deforesting" : 2, "Mining" : 2}, "index" : 109, "element" : ["elm1"]},
    {"name": "Frostallion", "rarity": 20, "skills": {"Cooling" : 4}, "index" : 110, "element" : ["elm2"]},
    {"name": "Frostallion Noct", "rarity": 20, "skills": {"Gathering" : 4}, "index" : 110, "element" : ["elm3"]},
    {"name": "Jetragon", "rarity": 20, "skills": {"Gathering" : 3, "Oil Extracting" : 3}, "index" : 111, "element" : ["elm2"]},
    {"name": "Bellanoir", "rarity": 20, "skills": {"Handiwork" : 2, "Medicine Production" : 4, "Transporting" : 2}, "index" : 112, "element" : ["elm2"]},
    {"name": "Bellanoir Libero", "rarity": 20, "skills": {"Handiwork" : 2, "Medicine Production" : 4, "Transporting" : 2}, "index" : 112, "element" : ["elm2"]},
    {"name": "Bellanoir Libero", "rarity": 20, "skills": {"Handiwork" : 2, "Medicine Production" : 4, "Transporting" : 2}, "index" : 112, "element" : ["elm2"]}
]

module.exports = data;